version: '3.7'

services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    logging:
      driver: "none"

  app1:
    build: .
    container_name: appc1
    depends_on:
      - consul
    environment:
      APP_MY_ID: appc1
      SERVICE_NAME: appc
    volumes:
      - ./:/go/app

  app2:
    build: .
    container_name: appc2
    depends_on:
      - consul
    environment:
      APP_MY_ID: appc2
      SERVICE_NAME: appc
    volumes:
      - ./:/go/app


  app3:
    build: .
    container_name: appc3
    depends_on:
      - consul
    environment:
      APP_MY_ID: appc3
      SERVICE_NAME: appc
    volumes:
      - ./:/go/app
