version: '3.7'

services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    logging:
      driver: "none"

  app1:
    build: .
    container_name: app1
    depends_on:
      - consul
    environment:
      APP_MY_ID: app1
      SERVICE_NAME: app
    volumes:
      - ./:/go/app

  app2:
    build: .
    container_name: app2
    depends_on:
      - consul
    environment:
      APP_MY_ID: app2
      SERVICE_NAME: app
    volumes:
      - ./:/go/app


  app3:
    build: .
    container_name: app3
    depends_on:
      - consul
    environment:
      APP_MY_ID: app3
      SERVICE_NAME: app
    volumes:
      - ./:/go/app

  app4:
    build: .
    container_name: app4
    depends_on:
      - consul
    environment:
      APP_MY_ID: app4
      SERVICE_NAME: app
    volumes:
      - ./:/go/app

  app5:
    build: .
    container_name: app5
    depends_on:
      - consul
    environment:
      APP_MY_ID: app5
      SERVICE_NAME: app
    volumes:
      - ./:/go/app