version: '3.7'

services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    logging:
      driver: "none"

  app1:
    image: acim/go-reflex
    container_name: app1
    depends_on:
      - consul
    environment:
      APP_MY_ID: app1
      SERVICE_NAME: app
    volumes:
      - ./:/app

  app2:
    image: acim/go-reflex
    container_name: app2
    depends_on:
      - consul
    environment:
      APP_MY_ID: app2
      SERVICE_NAME: app
    volumes:
      - ./:/app


  app3:
    image: acim/go-reflex
    container_name: app3
    depends_on:
      - consul
    environment:
      APP_MY_ID: app3
      SERVICE_NAME: app
    volumes:
      - ./:/app